arduino-libraries/ArduinoIoTCloud

src/ConnectionManager.h
src/WiFiConnectionManager.h

Fix a bug for the CONNECTION_STATE_GETTIME state that keep the state machine in this state in se of:
- loss of WiFi connection: in this case the fix will put the state in CONNECTION_STATE_DISCONNECTED and restart the WiFi connection loop
- inability to return a valid network time: in this case the fix will put the state in CONNECTION_STATE_DISCONNECTED after MAX_GETTIME_RETRY times and restart the WiFi connection loop

Managed exit cases for GETTIME state. Removed IDLE state.

---

src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h

Check MQTT status and transition in IOT_STATUS_CLOUD_RECONNECTING in case of loss of connection.

Managed exit cases for IOT_STATUS_CLOUD_CONNECTED, removed unused states

---

src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h

Reverts arduino-libraries/ArduinoIoTCloud#28
I have noticed some glitches during network connection if network time was not acquired promptly.
@ilcato let's review your changes again

Revert "Managed exit cases for IOT_STATUS_CLOUD_CONNECTED, removed unused states"

---

examples/ArduinoIoTCloud_LED_switch/ArduinoIoTCloud_LED_switch.ino
src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h
src/WiFiConnectionManager.h

ArduinoIoTCloudClass:
- defined DEFAULT_BROKER_PORT (see next)
- added brokerPort private member (uint16_t because of how it is defined in MQTT client)
- added possibility to pass an alternative Broker port after the address
- added getBrokerPort() method
- added printDebugInfo() method to ArduinoIoTCloud, to allow user to print out info useful for troubleshooting: Broker address:port, Thing ID, Device ID
WiFiConnectionManager:
- tweaked interval time for GETTIME
- added check for firmwareVersion() required version (delays 5 seconds if version is older than latest fixed ones, but still moves forward)
- cleaned up a couple of debugMessage formatted strings
Both:
removed *msgBuffer=0 from anywhere the buffer was filled with a new message

print troubleshooting info, added broker port, general cleanup

---

src/ConnectionManager.h

- `setDebugMessageLevel()` will now accept -1 to disable logging

possibility to disable logging

---

src/GSMConnectionManager.h
src/utility/NTPUtils.h

Changed NTP and ping endpoints to `time.arduino.cc`

Change ntp/ping server to the arduino ones

---

src/ArduinoIoTCloud.h

10 Hz data rate is too much for the actual use cases and the users use this feature when is not necessary so it better decrease to 2Hz.
Next step will be make this parameter configurable so the pro users can be publish until 10Hz

10 Hz data rate are too much for the actual use cases, decrease to 2Hz

---

src/ArduinoIoTCloud.cpp
src/GSMConnectionManager.cpp
src/GSMConnectionManager.h
src/WiFiConnectionManager.cpp
src/WiFiConnectionManager.h
src/utility/NTPUtils.cpp

Removed CONNECTION_STATE_GETTIME state in the connection manager classes. 
The status IOT_STATUS_CLOUD_CONNECTING and IOT_STATUS_CLOUD_RECONNECTING are able to loop until a valid time is returned. Furthermore, with the fallback to time.arduino.cc the need to retry has a very low probability.

Optimized getTime management

---

library.properties
src/ArduinoIoTCloud.cpp

Device will stay in mode `IOT_STATUS_CLOUD_CONNECTING` and display an error message for the user to inform him about the probable cause of the error.
```
[ 1742 ] ***** Arduino IoT Cloud - configuration info *****
[ 1742 ] Device ID: * 
[ 1743 ] Thing ID: *
[ 1743 ] MQTT Broker: mqtts-sa.iot.arduino.cc:8883
[ 2287 ] WiFi.status(): 0
[ 2288 ] Current WiFi Firmware: 19.5.4
[ 2288 ] Connecting to "my-wifi"
[ 26835 ] Connected to "my-wifi"
[ 27505 ] Connecting to Arduino IoT Cloud...
ERROR - Please verify your THING ID
```

[CM-474] Notify user if thing id is wrong / thing does not exist

---

src/ArduinoIoTCloud.cpp

- handling empty `_shadowTopicIn`
- preventing `_syncStatus` from being set to value other than `SYNC_STATUS_SYNCHRONIZED` when empty shadow topic

Fixing issue with sketches missing a Topic name (i.e.: Getting Started)

---

src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h
src/ConnectionManager.h
src/EthernetConnectionManager.cpp
src/GSMConnectionManager.cpp
src/WiFiConnectionManager.cpp

* Converting all enum's into enum classes will increase type safety (can't be mistaken for integers) while increasing readability.
* Braces for all switch-case statements prevent local variables from being visible in other case blocks than their own
**No changes to functional logic!**

Refactoring - Converting all enum's to enum classes + braces for all switch-case statements

---

.travis.yml
examples/ArduinoIoTCloud_LED_switch/ArduinoIoTCloud_LED_switch.ino
examples/ArduinoIoTCloud_LED_switch/arduino_secrets.h
examples/ArduinoIoTCloud_LED_switch/thingProperties.h
examples/ArduinoIoTCloud_Travis_CI/ArduinoIoTCloud_Travis_CI.ino
examples/ArduinoIoTCloud_Travis_CI/thingProperties.h
examples/utility/Provisioning/Provisioning.ino
src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h
src/CloudSerial.cpp
src/CloudSerial.h
src/ConnectionManager.h
src/EthernetConnectionManager.cpp
src/EthernetConnectionManager.h
src/GSMConnectionManager.cpp
src/GSMConnectionManager.h
src/WiFiConnectionManager.cpp
src/WiFiConnectionManager.h
src/utility/DebugUtils.cpp
src/utility/DebugUtils.h
src/utility/ECCX08Cert.cpp
src/utility/ECCX08Cert.h
src/utility/ECCX08TLSConfig.h
src/utility/NTPUtils.cpp
src/utility/NTPUtils.h

- Auto format code
- Add code formatting check to Travis CI build
- Use TravisBuddy to comment on PRs that result in a failed CI build
Check compliance with the Artistic Style code formatter configuration found in https://github.com/arduino/Arduino/blob/master/build/shared/examples_formatter.conf. A consistent style will be used for example sketches as well as library code.
This required first doing an auto format of all the code in the repository.
A TravisBuddy webhook was added to the Travis CI build. TravisBuddy will automatically comment on any pull request that results in a failing Travis CI build so that the author of the PR will get a notification of the issue and hopefully resolve it.
Example of a build failure caused by non-compliant code formatting: …

Add code formatting check to Travis CI build

---

.travis.yml
README.md

If any word is found that is on a list of commonly misspelled words, the Travis CI build will fail and a correction will be suggested in the build log.
[codespell](https://github.com/codespell-project/codespell) is a blacklist-based spell checker. This approach is more appropriate for a CI build because it results in far less false positives than would traditional whitelist-based spell checking, with the disadvantage of having more false negatives. So it won't catch all the typos, but it also won't be spuriously breaking every other build.
When false positives do occur, they can be resolved by adding the problematic word to `extras/codespell-ignore-words-list.txt`. Note that it was not necessary to add any words to the ignore list so this file is currently unnecessary. I added it anyway …

Check for commonly misspelled words during the CI build

---

.travis.yml

A lack of quotes on the shell variables caused the check to fail when there was a space in the path of a code file.

Make CI code formatting check support spaces in path

---

.travis.yml
examples/MultiValue_example/MultiValue_example.ino
examples/MultiValue_example/thingProperties.h

Due to the feedback received, it necessary to change the multi value properties in some way more compliance to the Arduino style. 
This type of initialization can be a solution
https://processing.org/reference/PVector.html
`location  = Location(latMov, lonMov);`
instead 
`Loc =   { .lat = latMov,   .lon = lonMov };`

Simplify multi value properties sketch

---

.travis.yml

Use [`arduino-cli`](https://github.com/arduino/arduino-cli) instead of the Arduino IDE for the Travis CI build.
`arduino-cli` does not result in the many "SocketListener" warnings that end up interspersed with the compilation output when using the Arduino IDE with Travis CI. These warnings make it more likely that Travis CI's maximum build log length will be exceeded, resulting in an errored job. The warnings also make the build log hard to read.
Due to a smaller download size, using `arduino-cli` results in a shorter CI build duration. In my test, the build duration was decreased from 13 min 53 sec to 10 min 5 sec.

Use arduino-cli for Travis CI build

---

.travis.yml

- In addition to the existing "All" compiler warning level (`-Wall -Wextra -Wno-expansion-to-defined`), add `-Wpedantic`
- Add `-Werror` to fail CI build if any warnings are encountered
`build.extra_flags` is used for other purposes in the Arduino SAMD Boards boards.txt so it would not have been ideal to use that property to set the warning flags. For this reason, I used `compiler.c.extra_flags`, `compiler.cpp.extra_flags`, and `compiler.S.extra_flags` instead.

Fail Travis CI build on compiler warnings

---

.travis.yml

There is a delay of hours before a library release becomes available for installation via Library Manager. For this reason, it's preferable to install library dependencies for the Travis CI build by cloning each library repository and checking out the newest Git tags.

Clone library dependencies for CI build

---

.travis.yml

This reverts commit f43c0fb7b19c179be5b9f49ee6acacbd58f83ed3.
It was eventually determined that failing the CI build on compiler warnings while compiling examples was too problematic due to the fact that warnings may be caused by external code.
Reference: https://github.com/arduino-libraries/ArduinoIoTCloud/pull/68#issuecomment-494687559

Revert "Fail Travis CI build on compiler warnings"

---

src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h

In 20cbb75e70d0360138189c5a8cf6992942ce1247 the implementation of
`ArduinoIoTCloudClass::update(int const reconnectionMaxRetries, int const reconnectionTimeoutMs)` 
was changed in such a way, that the function parameters `reconnectionMaxRetries` and `reconnectionTimeoutMs` ceased to have any meaning since they were no longer used. This fact was uncovered when enforcing stronger compile time checks in f43c0fb7b19c179be5b9f49ee6acacbd58f83ed3.
Capitalizing on this discovery we can drastically reduce the number of overloaded `update` functions provided. We may even remove the functions marked `deprecated` at a later point in time and we are left with a single `update` function.

Reducing available update functions

---

examples/ArduinoIoTCloud_ESP8266/thingProperties.h
examples/WiFi_Cloud_Blink_with_security_credentials/WiFi_Cloud_Blink_with_security_credentials.ino
examples/WiFi_Cloud_Blink_with_security_credentials/arduino_secrets.h
src/ArduinoIoTCloud.h

We need to had a new example sketch for the Getting Started flow for ESP8266.
Also, since the `DEVICE_LOGIN_NAME` was actually the board id, I changed it to `BOARD_ID`, which I believe makes more sense for the users.

Add new cloud blink sketch version working with security credentials

---

src/ArduinoIoTCloud.h
src/ArduinoIoTCloudLPWAN.cpp
src/ArduinoIoTCloudLPWAN.h
src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

This PR removes overloaded `update` functions which have been marked `deprecated` for quite some time. If users want to register a callback to be called when synchronisation is complete this should be done via `addCallback` instead of directly passing a function pointer to `update(CallbackFunc onSyncCompleteCallback)` which is removed within this PR.

Removing deprecated `update` functions

---

src/ArduinoIoTCloudTCP.h

`struct mqttConnectionOptions` is not used within the code, the keep alive interval and connection timeout are instead directly set [here](https://github.com/arduino-libraries/ArduinoIoTCloud/blob/master/src/ArduinoIoTCloudTCP.cpp#L186:L187).

Removing unused struct mqttConnectionOptions

---

.travis.yml

Hi @per1234 :wave: With this PR I intend to remove code formatting check from the Travis CI build because it just proves to be troublesome in the daily work (always leading to additional "code formatting" commits at the end of PRs). Now I know I was a strong supporter of this in the past but as long as not everyone working on this repository adopts a pre-commit auto-code-formatting hook (even I am guilty of not doing it) it will always lead to a polluted git history with a "let's fix this code formatting" commit at the end of every PR. If it's okay with your I would remove this check then.

Remove code formatting check during Travis CI build

---

src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

Cleaning up by removing pointer to a Client class which does not make sense any longer because we always use the connection handler to access any kind of connection

Removal of references to Client class since it's not used anymore.

---

src/ArduinoIoTCloudTCP.cpp

This allows class ArduinoCloudThing to obtain a 'epoch' timestamp which is used during synchronisation and which has been implemented so far via an 'extern' dependency to RTCZero. Since this kind of hidden dependency (basically a global object across 2 separate Arduino libraries) is very brittle the depdency is made clear by explicitly registering a function to provide the required timestamp.

Register a epoch timestamp retrieval function with ArduinoCloudThing

---

src/ArduinoIoTCloud.h
src/ArduinoIoTCloudLPWAN.cpp
src/ArduinoIoTCloudLPWAN.h
src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

This fixes #96.
The TCP load balancer of the Arduino IoT Cloud terminates a TCP connnection after 350 seconds. Unfortunately this termination is only detected after transmitting the next data set to the Arduino IoT Cloud. This has the unfortunate side effect that the data set sent to the cloud is lost. This change buffers every transmission to the server and requests a retransmission in case of loosing the connection.
**Note**: This can only happen if the keep-alive interval is set to a value > 350 seconds, e.g. to 1 hour:
```C++
_mqttClient->setKeepAliveInterval(60 * 60 * 1000);
```

Fix - Don't loose messages when MQTT connection was broken on message send

---

src/ArduinoIoTCloud.h
src/ArduinoIoTCloudLPWAN.cpp
src/ArduinoIoTCloudLPWAN.h
src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

This change is possible because of https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/25/commits/fa7446d48f567244c023db993f022234ae9fbe02 .

Remove depdendence of specialised connection handlers

---

src/ArduinoIoTCloudLPWAN.cpp

See [here](https://github.com/arduino-libraries/Arduino_ConnectionHandler/blob/9f42a6cb2c05cf9da54e1a892716c73b853ab8d5/src/Arduino_LoRaConnectionHandler.cpp#L51:L52).

Remove call to function init which is anyway implemented empty in LoRa_ConnectionHandler

---

.travis.yml

The previous configuration would only fail if the last compilation of one of the list items failed. Failure of any of the prior compilations in the list item would be masked by a successful final compilation.
For example, compilation of the `WiFi_Cloud_Blink` example is failing:
https://travis-ci.org/github/arduino-libraries/ArduinoIoTCloud/jobs/663401484#L1782
but the build is passing:
https://travis-ci.org/github/arduino-libraries/ArduinoIoTCloud/builds/663401482
The solution I chose is to use a single `buildSketch()` function instead of the `buildExampleSketch()` and `buildUtilitySketch()` functions. The example sketches to compile are passed as arguments to `buildSketch()`. The logic for determining the appropriate exit status is built into `buildSketch()`.

Fix false positives from CI build

---

.travis.yml
examples/ArduinoIoTCloud_LED_switch/arduino_secrets.h
examples/ArduinoIoTCloud_LED_switch/thingProperties.h
examples/ArduinoIoTCloud_Travis_CI/arduino_secrets.h
examples/ArduinoIoTCloud_Travis_CI/thingProperties.h

This pull requests adds the `MKR NB 1500` as build target for the Travis based CI process.

Adding MKR NB 1500 as built target for CI

---

.github/workflows/compile-examples.yml
.github/workflows/report-size-deltas.yml

On every push to a pull request, the change in memory usage of `examples/utility/ArduinoIoTCloud_Travis_CI` between the PR's head and base branch for each of the boards in the board matrix will be:
- Shown in the log
- Saved to a workflow artifact (you can see the artifact for this PR's run here: https://github.com/arduino-libraries/ArduinoIoTCloud/pull/116/checks?check_run_id=594325065)
- Commented to the PR's thread as a table (after a delay of ~7 minutes max.)
Demo:
https://github.com/per1234/ArduinoIoTCloud/pull/1#issuecomment-614684874
Partial fix for https://github.com/arduino-libraries/ArduinoIoTCloud/issues/112 (still need to add size trends reporting)

Report memory usage change caused by PRs

---

src/ArduinoIoTCloud.h
src/ArduinoIoTCloudLPWAN.cpp
src/ArduinoIoTCloudLPWAN.h
src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

The public `ArduinoIoTCloud` member methods `connect` and `disconnect` should not be called by the user of the library (they are called internally) and are therefore transformed to `protected` member functions. In the future a `end` function should be added (see #73) which works the opposite way to the the `begin` method and cleans everything up.

Reduce public API by turning connect/disconnect into protected methods.

---

README.md

The badge was not updated during the switch from Travis CI to GitHub Actions.
Fixes https://github.com/arduino-libraries/ArduinoIoTCloud/issues/120

Update CI status badges in readme

---

.github/workflows/unit-tests.yml
README.md
extras/test/CMakeLists.txt

On every pull request or push that changes relevant files (anything under `extras/test/` or `src/`):
- Run unit tests
- Print coverage report to the workflow log
- Upload coverage report to Codecov
This PR is dependent on https://github.com/arduino-libraries/ArduinoIoTCloud/pull/118. The workflow is currently expected to fail because the unit tests won't be added until https://github.com/arduino-libraries/ArduinoIoTCloud/pull/118 is merged.
Demonstration:
https://github.com/per1234/ArduinoIoTCloud/runs/646210541?check_suite_focus=true
https://codecov.io/github/per1234/ArduinoIoTCloud/commit/77fe90bb786f3e0843cb03b2839d1fd58c94995e
Fixes https://github.com/arduino-libraries/ArduinoIoTCloud/issues/119

Add GitHub Actions workflow to run unit tests and check code coverage

---

.github/workflows/compile-examples.yml

Running the Compile Examples GitHub Actions workflow is only necessary when files under `examples/`, `src/`, or the workflow configuration itself are modified. For any other changes, the workflow run only slows down the CI results and causes unnecessary comments from the report-size-deltas workflow.
Reference:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

Only run Compile Examples workflow when relevant files are modified

---

.github/workflows/compile-examples.yml

Use the matrix.include key to customize the compile-examples CI workflow's matrix jobs with board type-specific configurations.
This GitHub Actions feature allows defining additional properties for matrix jobs that match the filter:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
The previous approach for doing this was to use generated environment variable names, which worked but seemed likely to be confusing for anyone trying to decipher the workflow. I think the new approach is a little easier to understand and less hacky.
I had hoped this would allow me to do away with the `board.type` system, but supplying lists of values to the filter keys isn't supported, you can't reference the `env` key from matrix, and YAML anchors aren't …

Improve board-specific configuration system in compile-examples CI workflow

---

src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

This means that the memory consumption of those two rather large classes are directly visibale in the compilation output since ArduinoIoTCloud is instantiated as a global variable. The heap allocation is not directly visible to the user of the library and so gives the wrong impression that there is a lot of free space left.

Both MqttClient and BearSSLClient are allocated on the stack instead of the heap.

---

.github/workflows/compile-examples.yml

On every push to the master branch, size data will be written to a Google Sheets spreadsheet.
This information will allow tracking the trends in memory usage over time.
The first row of data (in addition to the column headings row) should written to [the spreadsheet](https://docs.google.com/spreadsheets/d/1I6NZkpZpf8KugBkE92adB1Z3_b7ZepOpCdYTOigJpN4) when this PR is merged.
---
Question: do you think it's best to have a single spreadsheet for the size trends reports for all repositories (one sheet in the spreadsheet per repository), or a separate spreadsheet for each repository. The former seems more convenient, but my concern is that we could hit some limit at a distant date in the future when there are lots of repositories with trends reports. The latter results in more clutter by …

Add size trends report step to CI workflow

---

.github/workflows/spell-check.yml
extras/codespell-ignore-words-list.txt
src/property/PropertyContainer.cpp

- Fix workflow format
- Fix misspelled word in comment that would cause the check to fail
- Exclude externally maintained resource folder that contains misspelled words
- Add name causing a false positive to the ignore list
- Remove entries from ignore list that are no longer needed now that it's possible to ignore paths containing externally maintained resources

Refresh spell check CI workflow

---

src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h
src/property/Property.cpp
src/property/Property.h
src/property/PropertyContainer.cpp
src/property/PropertyContainer.h

This new update policy allows to trigger the transmission of all properties when a certain function (`push`) is called. In order to configure a property for this update policy it must be initalized using the following syntax in `thing_properties.h`:
```C++
int seconds;
/* ... */
void initProperties()
{
ArduinoCloud.addProperty(seconds, Permission::Read).publishOnDemand();
```
In order to trigger the update the `ArduinoCloud.pushAll()` needs to be called. All properties are transmitted on the next call of `ArduinoCloud.update()`.
```C++
void loop()
{
/* ... */
ArduinoCloud.update();
/* ... */
ArduinoCloud.pushAll();
}
```
Successfully tested on PROD with
* `MKR WiFi 1010` :heavy_check_mark: 
* `MKR 1000` :heavy_check_mark: 
* `ESP8266` :heavy_check_mark:

Additional update policy "OnDemand"

---

extras/test/src/test_OTALogic.cpp
src/utility/ota/OTALogic.cpp
src/utility/ota/OTALogic.h
src/utility/ota/OTAStorage.h
src/utility/ota/OTAStorage_MKRMEM.cpp
src/utility/ota/OTAStorage_MKRMEM.h

This PR adds an additional "rename" step where the file used for storing the downloaded OTA image ("UPDATE.BIN.TMP") is renamed to the one expected by the [SFU](https://github.com/arduino/ArduinoCore-samd/tree/master/libraries/SFU) ("UPDATE.BIN"). This step is **only performed** when a **complete OTA image with valid checksum** has been received. As a result this PR prevents the failure scenario of the device being turned off during reception of the update image.
@manchoz :wave:

Use temporary file for storing the downloaded OTA image.

---

src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h

This PR deprecates this property initialisation approach
```C++
ArduinoCloud.addProperty(seconds, READ, ON_CHANGE, onSecondsChange);
```
in favour of
```C++
ArduinoCloud.addProperty(seconds, Permission::Read).publishOnChange();
```

Deprecate old c style functions for adding properties in favour of composition

---

extras/tools/README.md
extras/tools/bin2json.py
extras/tools/bin2ota.py
extras/tools/ota-upload.sh
src/ArduinoIoTCloud_Config.h
src/utility/ota/OTAStorage.h
src/utility/ota/OTAStorage_MKRGSM.cpp
src/utility/ota/OTAStorage_MKRGSM.h

In order to enable OTA you need to extend your sketch the following way:
```C++
#include <SSU.h>
#include <utility/ota/OTAStorage_MKRGSM.h>
/* ... */
static OTAStorage_MKRGSM ota_storage;
/* ... */
void setup()
{
ArduinoCloud.begin(ArduinoIoTPreferredConnection, "mqtts-sa.iot.oniudra.cc");
ArduinoCloud.setOTAStorage(ota_storage);
/* ... */
```
Furthermore you have to enable the MKR GSM as OTA storage module by editing `ArduinoIoTCloud_Config.h`
```diff
-  #define OTA_STORAGE_MKRGSM        (0)
+  #define OTA_STORAGE_MKRGSM        (1)
```
[gsm-json.zip](https://github.com/arduino-libraries/ArduinoIoTCloud/files/4879170/gsm-json.zip)
Upload to board via
```bash
./ota-upload.sh CLIENT_ID CLIENT_SECRET DEVICE_ID [gsm-ota.json|gsm-local.json]
```

Use the SARA U-201 modem for storing OTA update image.

---

src/ArduinoIoTCloudTCP.cpp

`updateTimestampOnLocallyChangedProperties` was called before a connection had been established which led to the time service having a wrong date configured (1/1/2000) which leads to an expired certificate which inhibits the establishment of a connection to the server since the certificate has expired. This was triggered when properties where changed within `setup`.
```C++
void setup()
{
/* ... */
property = 1337;
/* This caused updateTimestampOnLocallyChangedProperties to configure the time service
* before a network connection has been established. This causes a wrong certificate date
* which appears as if the certificate has expired.
*/
}
```
Behaviour with the bug present:
```
Arduino IoT Cloud Connection status: CONNECTING
Arduino IoT Cloud connecting ...
Arduino IoT Cloud connecting …
```

Bugfix: Changing value of property before loop prevents connection to cloud server.

---

src/utility/time/TimeService.cpp

Ensure that the returned time is at least the compile time of the sketch, otherwise we might have an error scenario where no connection is available which would lead to a timestamp of 0 which would lead to the certificate being declared 'expired' and the device will be unable to connect to the server

Fix: Use sketch compile time if no connection is available for estimating system time.

---

.github/workflows/compile-examples.yml

instead of MKRGSM:master:HEAD (was only required until the latest features GSMFileUtils had been [released](https://github.com/arduino-libraries/MKRGSM/releases/tag/1.5.0)).

Change github actions compile examples workflow back to use the latest release version

---

src/utility/ota/OTAStorage_SSU.cpp

Usage for uploading LZSS compressed file:
```bash
./lzss.py --encode gsm.bin gsm.lzss
./bin2ota.py gsm.lzss gsm.ota
./bin2json.py gsm.ota gsm.json
./ota-upload.sh CLIENT_ID CLIENT_SECRET DEVICE_ID gsm.json
```
Requires https://github.com/arduino/ArduinoCore-samd/pull/544.
Test files: [gsm-ota-test-bin.zip](https://github.com/arduino-libraries/ArduinoIoTCloud/files/4924821/gsm-ota-test-bin.zip)

Support LZSS capable SSU Bootloader

---

src/utility/ota/OTALogic.cpp
src/utility/ota/OTAStorage.h
src/utility/ota/OTAStorage_SFU.cpp
src/utility/ota/OTAStorage_SFU.h
src/utility/ota/OTAStorage_SNU.cpp
src/utility/ota/OTAStorage_SNU.h
src/utility/ota/OTAStorage_SSU.cpp
src/utility/ota/OTAStorage_SSU.h

taking into account that every SFU has slightly different semantics.

Refactor OTA Storage API

---

src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h
src/tls/utility/SHA256.cpp
src/tls/utility/SHA256.h
src/utility/ota/FlashSHA256.cpp
src/utility/ota/FlashSHA256.h
src/utility/ota/OTALogic.cpp

This PR calculate the **SHA256** checksum over the firmware stored in the flash of the MCU. The checksum is then stored 
as ASCII encoded hexadecimal number within a hidden character string property `OTA_SHA256`. 
**Note**: As we don't know the length per-se we read chunks of the flash until we detect one containing only 0xFF (= flash erased). This only works for firmware  updated via OTA and second stage bootloaders (SxU family) because only those erase the complete flash before performing an update.
Since the SHA256 firmware image is only required for the cloud servers to perform a version check after the OTA update this is a acceptable trade off. The bootloader is excluded from the calculation and occupies flash address range 0 to 0x2000, total flash size of 0x40000 bytes (256 kByte). …

Calculate SHA256 over firmware image uploaded via OTA

---

src/AIoTC_Config.h
src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h
src/ArduinoIoTCloudLPWAN.cpp
src/ArduinoIoTCloudLPWAN.h
src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h
src/property/PropertyContainer.h
src/utility/ota/FlashSHA256.cpp
src/utility/time/TimeService.cpp
src/utility/time/TimeService.h

... by rewriting into an integrated state machine making all necessary steps visible instead of hidden.

Restructure connection logic

---

.github/workflows/compile-examples.yml

... Since the SxU 2nd stage bootloaders have been released now.

Use ArduinoCore-samd - latest released version

---

.github/workflows/compile-examples.yml

Compile library examples for Arduino Portenta H7's M4 and M7 cores during CI run.
The workflow is configured to use the version of the Arduino mbed-Enabled Boards platform from the tip of the default branch of the ArduinoCore-mbed repository. This is necessary because compiling for the Portenta H7 M4 core board fails when using the current release version of the platform (1.2.2). The issue has been fixed (https://github.com/arduino/ArduinoCore-mbed/pull/33), so the [second commit of this PR](https://github.com/arduino-libraries/ArduinoIoTCloud/commit/24edb4b439c3b1624efbbb313b6698314e721aaa) can be reverted after the next release of the Arduino mbed-Enabled Boards platform.
Fixes https://github.com/arduino-libraries/ArduinoIoTCloud/issues/180

Add Portenta boards to Compile Examples CI workflow

---

extras/test/CMakeLists.txt

Disabling `-Wcast-function-type` for FakeIt mocking framework and `-Wdeprecated-copy` for cloud data types (both cause warnings which become errors when compiling with `-Werror` and `GCC 9.3.0`.

Disable warnings when compiling test code -Werror and GCC 9.3.0

---

src/ArduinoIoTCloudTCP.cpp

If the nina fw is < 1.4.1 the following statement is written to the Serial
```
ArduinoIoTCloudTCP::begin error nina firmware needs to be >= 1.4.1, current 1.3.0
```
@eclipse1985

Produce warning when running with nina-fw version < 1.4.1 (required for OTA).

---

README.md

Since the Device Manager doesn't manage IoT devices anymore, we have to remove the link from README

Remove link to device manager

---

src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

Add hiddden property OTA_CAP for signaling OTA update capability

---

.github/workflows/compile-examples.yml

Wherever possible use the latest released version when loading external libraries for CI (this better reflects the user experience who typically has the latest released version, not the latest commit from master.

[CI] Use latest released version for Arduino_DebugUtils, Arduino_ConnectionHandler, WiFiNINA

---

src/ArduinoIoTCloudTCP.cpp

Only set hidden property OTA_CAP to true if the nina firmware version is >= 1.4.1

---

library.properties

Previously, when compiling the library for Portenta H7, a [confusing](https://forum.arduino.cc/index.php?topic=704905) warning was displayed:
```
WARNING: library ArduinoIoTCloud claims to run on samd, esp8266 architecture(s) and may be incompatible with your current board which runs on mbed architecture(s).
```

Add "mbed" to list of supported architectures

---

src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

This fixes the situation, that if a previous OTA download failed, the used would not get accurate information on a retry since the error would not be cleared in between. CC @eclipse1985

Reset OTA error before new OTA download

---

src/ArduinoIoTCloudTCP.cpp

Instead of
```
ArduinoIoTCloudTCP::handle_SubscribeMqttTopics could not subscribe to /a/t/THING_ID/e/i
```
display
```
ArduinoIoTCloudTCP::handle_SubscribeMqttTopics could not subscribe to /a/t/THING_ID/e/i
Check your thing configuration, and press the reset button on your board.
```

Improve error message when wrong thing id is configured.

---

.github/workflows/compile-examples.yml
.github/workflows/report-size-deltas.yml

The "smoke test" sketch compilation and reporting actions have been moved to dedicated repositories. The actions hosted at the old `arduino/actions/libraries/*` location will no longer be maintained.
Since the time the actions were migrated to the dedicated repositories, a breaking change was made to the default value of the `sketches-report-path` input, which required a change to the values of the `name` and `path` inputs of the `actions/upload-artifact` action.
Since the time the "Compile Examples" workflow was written, some improvements have been made to the API of the `arduino/compile-sketches` CI action. The previous API is still supported, but is deprecated and warnings are displayed in the workflow run log about this, which could result in confusion for contributors.
---
GitHub …

Use sketch compilation CI actions from their new dedicated repositories

---

.github/workflows/compile-examples.yml

Previously, the `namespace_arduino` branch of ArduinoCore-API was used in the core library of the development version of
the Mbed OS Boards platform used in the "Compile Examples" CI workflow. The default branch of ArduinoCore-API is now the
latest and greatest version, so the `namespace_arduino` branch should no longer be used for the Mbed OS Boards platform's core library (https://github.com/arduino/ArduinoCore-mbed/commit/3c175d7e4df9bbd19d65b5285f163785f28d0fbc).
In combination with https://github.com/arduino-libraries/ArduinoIoTCloud/pull/213, this fixes the CI compilataion for the `arduino:mbed` boards.

Use default branch of ArduinoCore-API in CI workflow

---

.github/workflows/compile-examples.yml

The symlink for ArduinoCore-API in the Mbed OS Boards core library has been removed (https://github.com/arduino/ArduinoCore-mbed/commit/ca397e88926c16ccfd7531f842a2d8f0971dcffc). This resulted in the step of the "Compile Examples" CI workflow that removes the now non-existent symlink to fail.
---
Even though the CI still fails, I believe this is a legitimate failure, rather than a misconfiguration of the workflow.

Remove api symlink deletion step from CI workflow

---

.github/workflows/compile-examples.yml
examples/ArduinoIoTCloud-Basic/ArduinoIoTCloud-Basic.ino
src/cbor/lib/tinycbor/src/open_memstream.c

ESP32 support has been added to the library (https://github.com/arduino-libraries/ArduinoIoTCloud/pull/211), so the examples compilation smoke test should be done for this architecture as well.
Fixes https://github.com/arduino-libraries/ArduinoIoTCloud/issues/215

Add ESP32 board to "Compile Examples" CI workflow

---

.github/workflows/compile-examples.yml

When the version is not pinned, the latest release is used (currently 0.14.0). This version has an incompatibility with
the combination of ArduinoIoTCloud and ESP8266 (https://github.com/arduino-libraries/ArduinoIoTCloud/issues/216):
https://github.com/arduino-libraries/ArduinoIoTCloud/runs/1695624922?check_suite_focus=true#step:8:266
```
/home/runner/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: /tmp/arduino-sketch-E7F14C7104ED32E659A1CD76F63C3596/libraries/ESP8266WiFi/objs.a: member /tmp/arduino-sketch-E7F14C7104ED32E659A1CD76F63C3596/libraries/ESP8266WiFi/objs.a(ESP8266WiFi.a) in archive is not an object
```
The easy workaround is to use the previous Arduino CLI version to get
the CI …

Pin Arduino CLI version used in CI to 0.13.0

---

.github/workflows/compile-examples.yml

Previously, the most recent release of the ESP8266 boards platform (currently 2.7.4) was used in the "Compile Examples"
CI workflow. Arduino Create uses 2.5.0, so it's best to use that version for testing as well.

Pin esp8266:esp8266 platform version to 2.5.0 in CI builds

---

.github/workflows/compile-examples.yml

This reverts commit 1ffe81137251c052d5978c051d9022d4912bb9c3.
1ffe81137251c052d5978c051d9022d4912bb9c3 was a temporary workaround for a bug in Arduino CLI 0.14.0.
This was fixed (https://github.com/arduino/arduino-cli/pull/1140) with the release of Arduino CLI 0.14.1 so we are now able to go back to using the latest Arduino CLI version in the "Compile Examples" CI workflow.
Fixes https://github.com/arduino-libraries/ArduinoIoTCloud/issues/216

Revert "Pin Arduino CLI version used in CI to 0.13.0 (#222)"

---

src/AIoTC_Config.h

Until we figure out an upgrade path for all current MKR WIFI 1010, NANO 33 IOT users.
CC @facchinm

Reversion: Only use BearSSL offload for Uno WiFi Rev. 2

---

src/ArduinoIoTCloudTCP.cpp
src/tls/BearSSLClient.cpp
src/tls/BearSSLClient.h

This fixes #86 and #221 (:pray:). @jcham @IgorSchelle can you please test?
CC @eclipse1985 @zmoog can please you test on your setup too?

Improve reliability on connection loss

---

.github/workflows/compile-examples.yml
src/ArduinoIoTCloudTCP.cpp
src/utility/watchdog/Watchdog.h

Which is continually fed within `ArduinoIoTCloud::update()` to reset the board in case some function becomes stuck.

Adding watchdog for SAMD architecture

---

examples/ArduinoIoTCloud-Callbacks/ArduinoIoTCloud-Callbacks.ino

I found an error in the Callbacks example when I was looking for a solution to a problem I was having with a project. It was the callback for what to do on disconnect. 
It was written:
```
ArduinoCloud.addCallback(ArduinoIoTCloudEvent::CONNECT, doThisOnDisconnect);
```
And I changed it to:
```
ArduinoCloud.addCallback(ArduinoIoTCloudEvent::DISCONNECT, doThisOnDisconnect);
```
Which I think is what it was meant to be.
This is my first time contributing to any Arduino project, so I apologize for breaking any conventions or not following proper protocol.

fix typo in the ArduinoIoTCloud-Callbacks example

---

.github/workflows/compile-examples.yml
src/AIoTC_Config.h
src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h
src/utility/watchdog/Watchdog.cpp
src/utility/watchdog/Watchdog.h

Therefore freeing a considerate amount of Flash/RAM on ATSAMD21G18.
Supersedes #234.

Enable BearSSL Offload for MKR WiFi 1010 and Nano 33 IoT

---

.codespellrc
.github/workflows/compile-examples.yml
.github/workflows/report-size-deltas.yml
.github/workflows/spell-check.yml
extras/codespell-ignore-words-list.txt

- Update action versions used in sketch compilation workflows (https://github.com/arduino-libraries/ArduinoIoTCloud/commit/502162c07fd691972d70c11c507d5b8fbe28c72a)
- Use [official GitHub Actions action](https://github.com/codespell-project/actions-codespell) for spell checking (https://github.com/arduino-libraries/ArduinoIoTCloud/commit/d92324ea625acfc6c96a386b7ba60daadbd9d4e1)
- Fix comments and formatting of workflow (https://github.com/arduino-libraries/ArduinoIoTCloud/commit/fd2eff8003d7444a0756813f44bf0eadd0462ab0, https://github.com/arduino-libraries/ArduinoIoTCloud/commit/c1f0077ad53b2af4ee6b429c26d4ca50e995f6bf)

Modernize CI system

---

src/ArduinoIoTCloudTCP.cpp

The individual function calls during the OTA binary download process can take quite a lot of time. As the OTA callback is called from within the update() method the watchdog is not reset in its regular manner. As a consequence the watchdog needs to be fed/kicked/reset during the various OTA download steps in order to avoid a premature reset caused by watchdog-timeout.

Feed Portenta H7 watchdog during OTA.

---

src/ArduinoIoTCloudTCP.cpp

Since we'll be only using nina-fw:v1.4.4 and forward for SSL offloading the outdated warning concerning v1.4.3 needs to be replaced with 1.4.4.

Fix: Correct required nina-fw version for SSL stack offloading

---

src/ArduinoIoTCloudTCP.cpp

It does not make sense to let the user wait until the timeout has passed (which is now even 30 seconds) long. Therefore the logic should trigger an immediate sync the first time this function is reached.

Fix: Immediately trigger a sync request on the first time this function is reached

---

src/ArduinoIoTCloudTCP.cpp

Previously a call to this method had to be omitted, it was only required for ESP8266.
Out of a debugging session ended up with the broker refusing connections so I enabled `insecure` mode and it now works

enabled `setInsecure()` for ESP32

---

src/ArduinoIoTCloudTCP.cpp
src/utility/ota/OTA-portenta-h7.cpp
src/utility/ota/OTA-samd.cpp
src/utility/ota/OTA.h

* `MKR WiFi 1010` :heavy_check_mark: 
* `Portenta H7` :heavy_check_mark:

Refactor OTA request handler code

---

.github/workflows/compile-examples.yml

The current implementation is barely working, as it is exceeding the flash storage capacity of the Uno WiFi Rev. 2. It makes no sense for us to trouble us with a "failing CI build", when we are not really supporting Arduino Uno WiFi Rev. 2 at all."

Disable CI compilation for Uno WiFi Rev. 2

---

library.properties

The library does not support the megaavr architecture, so the metadata was incorrect.
Reference: https://github.com/arduino-libraries/ArduinoIoTCloud/pull/254

Remove claim of compatibility with megaavr architecture

---

.github/workflows/compile-examples.yml

I should already have done that with #254 since what do we have a CVS for if not for keeping track of all the changes ;) (Meaning the CI code can easily be restored).

Remove commented-out CI code for Uno WiFi Rev. 2.

---

src/ArduinoIoTCloudTCP.cpp
src/utility/ota/OTA-nano-rp2040.cpp
src/utility/ota/OTA-portenta-h7.cpp
src/utility/ota/OTA-samd.cpp
src/utility/watchdog/Watchdog.cpp
src/utility/watchdog/Watchdog.h

Aim of this pr is to cleanup watchdog handling replacing architecture specific function calls with an unique implementation that actually takes care of the architecture.
I've added also an out of scope commit that fixes the declared NANO_RP2040 maximum watchdog timeout.
I didn't change the `mbed_watchdog_trigger_reset` function with the hope to find a better fix in the future and remove it.
I'm opening as a draft to start testing.
| Board  | Result |
| ------------- | ------------- |
| NANO RP2040  | :heavy_check_mark:|
| PORTENTA H7  |   |
| NANO 33 IoT |:heavy_check_mark: |
| MKR WIFI 1010 |:heavy_check_mark: |

Watchdog handling cleanup

---

src/ArduinoIoTCloudTCP.cpp
src/utility/ota/OTA-portenta-h7.cpp

Needs https://github.com/arduino-libraries/Arduino_Portenta_OTA/pull/10
TODO drop Enable debug output commit

Wdog trigger during binary download decompressio for portenta

---

library.properties

When installing ArduinoIoTCloud this required library is not installed and compilation fails

added Adafruit_SleepyDog library to dependencies

---

.github/workflows/check-arduino.yml
README.md

On every push, pull request, and periodically, run Arduino Lint to check for common problems not related to the project
code.

Add CI workflow to do Arduino project-specific linting

---

README.md

Fixed by replacing ArduinoIoTCloud with ArduinoCloud.
This fixes #269.

Bugfix: Typo within Watchdog section of FAQ

---

src/property/Property.h

Using this [sketch](https://create-dev.arduino.cc/editor/eclipse85/b18100b3-739e-4940-abae-15cae42993a4/preview?F=thingProperties.h) assigning from the dashboard the vale of 1609459800 to `time2` variable it will result to print 1609459840.
Looking at [CborMapData](https://github.com/arduino-libraries/ArduinoIoTCloud/blob/41660e01a813de414c6e26fdfe4119465d78ffaa/src/property/Property.h#L104) class, the  1609459800 value is stored into a `float` variable and its hexadecimal rapresentation will be 0x4EBFDCD1; going back to `int` we will get 1609459840.
Storing the value in a double variable will avoid conversion errors.
I've used this web converters to check conversion error:
- https://babbage.cs.qc.cuny.edu/ieee-754.old/Decimal.html
- https://babbage.cs.qc.cuny.edu/ieee-754.old/32bit.html …

Change val MapEntry from float to double

---

extras/test/src/test_decode.cpp
extras/test/src/test_encode.cpp
src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h
src/property/Property.cpp
src/property/Property.h
src/property/PropertyContainer.h
src/property/types/CloudUnsignedInt.h
src/property/types/CloudWrapperUnsignedInt.h

This pr adds a new `CloudUnsignedInt` type and changes `CloudTime` from `CloudFloat` to `CloudUnsignedInt`
/cc @eclipse1985

Change CloudTime from CloudFloat to CloudUnsignedInt

---

src/property/Property.cpp

since #273 has been merged this message is not longer valid for PORTENTA.

Do not write "No RTC available..." message for PORTENTA target

---

library.properties

The `depends` field of [the library.properties metadata file](https://arduino.github.io/arduino-cli/dev/library-specification/#library-metadata) can be used to provide a list of library dependencies that should be installed in addition during a Library Manager installation. The library names must match exactly to the `name` value in the dependency's library.properties metadata file, which is the unique identifier used by Library Manager.
The name of the "Adafruit SleepyDog Library" [is just like that](https://github.com/adafruit/Adafruit_SleepyDog/blob/1.5.0/library.properties#L1), but an incorrect name "Adafruit_SleepyDog" was used instead when attempting to add it to the dependencies list. This resulted in the following:
- Classic Arduino IDE: the incorrect name was ignored and the …

Correct library dependency name in metadata

---

examples/ArduinoIoTCloud-Advanced/thingProperties.h
examples/ArduinoIoTCloud-Basic/thingProperties.h
examples/ArduinoIoTCloud-Callbacks/thingProperties.h

This needs to be added after Arduino_ConnectionHandler [0.6.5 release ](https://github.com/arduino-libraries/Arduino_ConnectionHandler/releases/tag/0.6.5)

Add missing channelMask parameter

---

examples/ArduinoIoTCloud-DeferredOTA/ArduinoIoTCloud-DeferredOTA.ino
examples/ArduinoIoTCloud-DeferredOTA/arduino_secrets.h
examples/ArduinoIoTCloud-DeferredOTA/thingProperties.h
src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

@facchinm i've took your PR #265 and made some small changes:
- removed default transport overriding
- Added https://github.com/arduino-libraries/ArduinoIoTCloud/commit/bfe9e1c05510cead57ea1300f6bac9316c21b86f https://github.com/arduino-libraries/ArduinoIoTCloud/commit/00f61ba7df82649a40dce98412de4d27b3a08b06 in order to sync `_ota_req` variable with the cloud and be able to start a deferred OTA after a board reset.
- some other minor cosmetic change
Having this feature has some minor drawbacks:
- last_values message size is increased
- if for some reason the library fails to send the cleared _ota_req flag to the cloud then `onOTARequestCb()` will be called again even if the OTA update was already applied.
Tests:
WebIDE OTA:
Board |  Test
--- | ---
MKR WiFi 1010 | :heavy_check_mark: …

Deferred OTA

---

src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

Switching to  ArduinoIoTCloud 1.3.0 from earlier version can lead to an OTA loop caused by bad synchronization of OTA_REQ property. The OTA loop occurs when the resulting CBOR message created calling sendPropertiesToCloud() is greater than 256 byte and thus it gets splitted in multiple parts. If the OTA variables are not synched within the firs part of the message the OTA process restart before the remainig properties are synched.
With this PR the OTA properties are synched all together within the same CBOR message ensuring a correct synchronization.
Updating an application builded with an ArduinoIoTCloud library < 1.3.0 with an OTA will still lead to an OTA process executed two times.
Thanks @eclipse1985 for spotting this.
/cc @zmoog

Fix OTA properties synchronization

---

src/property/Property.cpp
src/utility/time/TimeService.cpp
src/utility/time/TimeService.h

ArduinoCore-mbed has introduced support for RP2040 RTC and this patch makes it available for IoTCloud.

Enable RTC support for NANO_RP2040_CONNECT

---

src/AIoTC_Config.h

Some platforms do not define `ARDUINO_ARCH_ESP32` in favour of their own (see InkPlate's `ARCH_ARDUINO_INKPLATE).
This will cause compilation to fail for those devices.
Since every `ESP32` core defines `ESP32`, this has been added to the ARCH test in order to define `BOARD_ESP`

added definition of generic ESP32 to ARCH test

---

examples/ArduinoIoTCloud-Schedule/ArduinoIoTCloud-Schedule.ino

removing MKR WAN boards from the header of ArduinoIoTCloud-Schedule.ino example sketch because MKR WAN have no information about time so the scheduler wont work.

Minor change: Schedule example sketch: Fix supported boards list

---

src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h
src/tls/AIoTCSSCert.h
src/tls/bearssl/dec32be.c
src/tls/bearssl/enc32be.c
src/tls/bearssl/sha2small.c
src/tls/utility/Cert.cpp
src/tls/utility/Cert.h
src/tls/utility/CryptoUtil.cpp
src/tls/utility/CryptoUtil.h

This PR should be rebased and applied after #307 so only commits from https://github.com/arduino-libraries/ArduinoIoTCloud/commit/44a5920ddbd07c796397d7d1526df02d8d59830f to https://github.com/arduino-libraries/ArduinoIoTCloud/commit/3d79839629d963e80ce09cc5bc39c2a6b9562684 are meaningful. I did not found a better way to stack PRs from a fork...
Its goal is to prepare the library and add support to the `SE050` crypto device.
As of now this `SE050` can be found on `PORTENTA H7` boards, but it is not yet enabled in AIoTC_Config.h neither supported by the core.

Prepare library to support SE050 crypto device

---

.github/workflows/compile-examples.yml
library.properties
src/AIoTC_Config.h
src/ArduinoIoTCloudTCP.cpp
src/utility/ota/OTA-portenta-h7.cpp
src/utility/ota/OTA.h
src/utility/watchdog/Watchdog.cpp

This PR finalize the work done in #307 and #308 adding a new supported board

Add support for NICLA VISION

---

.github/workflows/compile-examples.yml
src/AIoTC_Config.h
src/ArduinoIoTCloudTCP.cpp
src/utility/ota/OTA-portenta-h7.cpp
src/utility/ota/OTA.h
src/utility/watchdog/Watchdog.cpp

With the actual configuration of the library OTA is not enabled for PORTENTA_H7_M4:
https://github.com/arduino-libraries/ArduinoIoTCloud/blob/45d5672c4473c9663720dc1f187c03bffce46c6e/src/AIoTC_Config.h#L105-L115
so is it safe to not compile `portenta_h7_onOTARequest()` function for the M4 build.
This is also a possible fix for the compile-examples failure of the last release caused by restricting the support of Arduino_Portenta_OTA only to the M7 core:
https://github.com/arduino-libraries/Arduino_Portenta_OTA/blob/0652134e737b67575e2d1c41cb9fac238922ebd0/src/Arduino_Portenta_OTA_Config.h#L27-L31

PORTENTA_H7_M4: Remove M4 core from supported build options

---

README.md

- link to the core version used in the online builder
- Authentication scheme
- Watchdog
- RTC

Add some notes in the README about ESP devices

---

library.properties

ESP32 architecture is currently supported through thid-party [arduino-esp32](https://github.com/espressif/arduino-esp32/releases/tag/1.0.6) core version1.0.6

Add esp32 architecture in library.properties file

---

.github/workflows/compile-examples.yml
examples/utility/SelfProvisioning/ECCX08Cert.cpp

The code formerly integrated in ArduinoBearSSL has long since been integrated with ArduinoIoTCloud library.

Remove ArduinoBearSSL as a CI build dependency.

---

.github/workflows/compile-examples.yml

This will also fix this Ci compile examples error :
* https://github.com/arduino-libraries/ArduinoIoTCloud/runs/8249064624?check_suite_focus=true

CI: Use mbed_portenta core release instead of ArduinoCore-mbed HEAD

---

.github/workflows/unit-tests.yml

The runtime-path input is deprecated. We should use runtime-paths instead. See :
* https://github.com/arduino-libraries/ArduinoIoTCloud/runs/8249063541?check_suite_focus=true

Fix Unexpected input warning running unit-tests workflow

---

src/AIoTC_Config.h
src/ArduinoIoTCloudTCP.cpp
src/utility/ota/OTA-portenta-h7.cpp
src/utility/ota/OTA.h
src/utility/watchdog/Watchdog.cpp

This will hopefully reduce the number of changes needed adding new stm32h7 boards.

Add common define for STM32H7 boards

---

examples/ArduinoIoTCloud-Advanced/thingProperties.h
examples/ArduinoIoTCloud-Basic/thingProperties.h
examples/ArduinoIoTCloud-Callbacks/thingProperties.h
examples/ArduinoIoTCloud-DeferredOTA/thingProperties.h
examples/ArduinoIoTCloud-Schedule/thingProperties.h
examples/utility/ArduinoIoTCloud_Travis_CI/thingProperties.h

After release [1.5.0](https://github.com/arduino-libraries/ArduinoIoTCloud/releases/tag/1.5.0) is no more necessary to configure the `thing_id` from the sketch. The board retrieves  the attached `thing_id` from the cloud  using the `device_id`.
Fixes #304

Remove setThingId(THING_ID) from library examples

---

src/ArduinoIoTCloudTCP.cpp
src/utility/ota/OTA-portenta-h7.cpp
src/utility/ota/OTA.h
src/utility/watchdog/Watchdog.cpp
src/utility/watchdog/Watchdog.h

Needs: 
* https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/81 and 
https://github.com/arduino/ArduinoCore-mbed/pull/526 for Ethernet connection
* https://github.com/arduino-libraries/Arduino_Portenta_OTA/pull/30 for OTA

Add ethernet interface support (OTA and Watchdog) for Portenta H7

---

README.md
examples/ArduinoIoTCloud-Advanced/ArduinoIoTCloud-Advanced.ino
examples/ArduinoIoTCloud-Advanced/arduino_secrets.h
examples/ArduinoIoTCloud-Advanced/thingProperties.h
examples/ArduinoIoTCloud-Basic/ArduinoIoTCloud-Basic.ino
examples/ArduinoIoTCloud-Basic/arduino_secrets.h
examples/ArduinoIoTCloud-Basic/thingProperties.h
examples/ArduinoIoTCloud-Callbacks/ArduinoIoTCloud-Callbacks.ino
examples/ArduinoIoTCloud-Callbacks/arduino_secrets.h
examples/ArduinoIoTCloud-Callbacks/thingProperties.h
examples/ArduinoIoTCloud-DeferredOTA/ArduinoIoTCloud-DeferredOTA.ino
examples/ArduinoIoTCloud-DeferredOTA/arduino_secrets.h
examples/ArduinoIoTCloud-DeferredOTA/thingProperties.h
examples/ArduinoIoTCloud-Schedule/ArduinoIoTCloud-Schedule.ino
examples/ArduinoIoTCloud-Schedule/arduino_secrets.h
examples/ArduinoIoTCloud-Schedule/thingProperties.h
examples/utility/ArduinoIoTCloud_Travis_CI/ArduinoIoTCloud_Travis_CI.ino
examples/utility/ArduinoIoTCloud_Travis_CI/arduino_secrets.h
examples/utility/ArduinoIoTCloud_Travis_CI/thingProperties.h

Add EthernetConnectionHandler in library examples and the list of ethernet enabled boards in the readme.
Bonus: 
https://github.com/arduino-libraries/ArduinoIoTCloud/commit/0802445d458a84cebdb9ac306beae4cd0395544a Make Basic example build for all ESP32 boards
https://github.com/arduino-libraries/ArduinoIoTCloud/commit/7c4eb0938a463446974629938c3efc52bdfde5b9 Align header format of library examples

Ethernet: examples and readme update

---

README.md
src/property/Property.cpp
src/utility/time/TimeService.cpp
src/utility/time/TimeService.h

Using ESP boards each `ArduinoCloud.update()` call is firing an NTP request introducing potentially long delays in the `loop()`.
* ESP32 boards have an internal RTC that can be configured and readed using core API.
* ESP8266 do not have an internal RTC so the value is synced once a day with the NTP server and updated using `millis()`.
Fixes #319

ESP TimeService: remove delays introduced by NTP requests

---

src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h
src/ArduinoIoTCloudTCP.cpp

During the `thing_id` discovery work https://github.com/arduino-libraries/ArduinoIoTCloud/pull/297 i've added unnecessary methods to the public space.
The goal of this pr is to:
reorder `addPropertyReal` methods in ArduinoIoTCloud.cpp to make more clear who is calling who
remove unnecessary `addPropertyReal` methods from public space: the user should not be able to select the property container because all user properties have to be added to the `_thing_property_container`.

Reorder and simplify addPropertyReal methods 

---

.github/workflows/compile-examples.yml
library.properties
src/AIoTC_Config.h

~~Need to add CI~~
Needs:
* https://github.com/arduino-libraries/Arduino_Portenta_OTA/pull/34
* https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/87

Add support for opta board

---

extras/tools/bin2ota.py

Now it looks like:
elif board == "NICLA_VISION":

bin2ota Fix: Add missing colon

---

library.properties

This is probably a regression: compilation fails on ESP32 when the new Arduino_ESP32_OTA is not installed. This PR adds it to dependencies so that it's automatically installed.

Add Arduino_ESP32_OTA to library dependencies

---

src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h
src/utility/ota/OTA-esp32.cpp
src/utility/ota/OTA-nano-rp2040.cpp
src/utility/ota/OTA-portenta-h7.cpp
src/utility/ota/OTA-samd.cpp
src/utility/ota/OTA.cpp
src/utility/ota/OTA.h

Following https://github.com/arduino-libraries/ArduinoIoTCloud/pull/350/commits/1ab8b3f23a3993038254e571e785ffe26f6f2195
Tests:
| Board  | OTA |
| ------------- | ------------- |
| NANO RP 2040 Connect  | :shipit:  |
| MKR WIFi 1010  | :shipit: |
| PORTENTA  | :shipit: |
| ESP32  | :shipit: |
| NICLA VISION  | :shipit: |
| OPTA | :shipit: |

Ota: move code

---

src/utility/time/TimeService.cpp

Some user reported a wrong behaviour of the scheduler widget due to wrong time. After some investigations we discovered that the time readed from connection handler was wrong. 
https://forum.arduino.cc/t/arduino-cloud-scheduler-responding-to-utc-time-instead-of-local-time/992909/21
The issue needs some more investigation to understand if the root cause is a wrong time injected from the provider or some bug in the [MKRNB library](https://github.com/arduino-libraries/MKRNB/blob/e94641fba4a81dfaa72f13175cfe67e1a5b091ce/src/NB.cpp#L443 ), but it looks a good idea to change the priority of the time sources and use NTP as first choice and the connection handler as fallback.

Use NTP as primary time source and connection handler as fallback

---

src/AIoTC_Config.h

`ARDUINO_ARCH_ESP8266` and `ESP8266` are both defined when building a sketch for ESP 8266/8285 platform.
Same thing for `ARDUINO_ARCH_ESP32` and `ESP32`.
`ARDUINO_ESP8266_ESP12` is a board configuration define and is not needed.

ESP: Remove redundant arch defines

---

examples/ArduinoIoTCloud-Advanced/arduino_secrets.h
examples/ArduinoIoTCloud-Advanced/thingProperties.h
examples/ArduinoIoTCloud-Basic/arduino_secrets.h
examples/ArduinoIoTCloud-Basic/thingProperties.h
examples/ArduinoIoTCloud-Callbacks/arduino_secrets.h
examples/ArduinoIoTCloud-Callbacks/thingProperties.h
examples/ArduinoIoTCloud-DeferredOTA/arduino_secrets.h
examples/ArduinoIoTCloud-DeferredOTA/thingProperties.h
examples/ArduinoIoTCloud-Schedule/arduino_secrets.h
examples/ArduinoIoTCloud-Schedule/thingProperties.h
examples/utility/ArduinoIoTCloud_Travis_CI/arduino_secrets.h
examples/utility/ArduinoIoTCloud_Travis_CI/thingProperties.h
src/AIoTC_Config.h
src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h

Theoretically more board can use username and password authentication and probably more board are coming using this authentication method. Renaming this configuration define will make code more clear and readable.

Configuration: Add BOARD_HAS_SECRET_KEY

---

.github/workflows/unit-tests.yml

[Codecov](https://codecov.io) claims a token is not needed when using the [`codecov/codecov-action`](https://github.com/codecov/codecov-action) GitHub Actions action in workflows of a public repository:
https://github.com/codecov/codecov-action#usage
> For public repositories, no token is needed
However, experience shows that that step of the workflow is subject to intermittent spurious failures caused by a 404 error during the upload attempt:
https://github.com/arduino-libraries/ArduinoIoTCloud/actions/runs/5403452364/jobs/9816277077#step:4:32
```
[2023-06-28T16:21:33.805Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': …
```

Use token when uploading unit test code coverage data to Codecov from workflow

---

.github/workflows/compile-examples.yml
library.properties
src/AIoTC_Config.h
src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h
src/utility/time/TimeService.cpp

To connect to ArduinoIoTCloud WiFi firmware need to be updated. The minimum required version is `0.2.0`.
Pre release of the firmware is available here: https://github.com/bcmi-labs/uno-r4-wifi-usb-bridge/releases
Updater tool for [linux](https://github.com/bcmi-labs/uno-r4-wifi-usb-bridge/releases/download/0.2.0/unor4wifi-update-linux.zip), [win](https://github.com/bcmi-labs/uno-r4-wifi-usb-bridge/releases/download/0.2.0/unor4wifi-update-windows.zip), [macos](https://github.com/bcmi-labs/uno-r4-wifi-usb-bridge/releases/download/0.2.0/unor4wifi-update-macos.zip).
Instructions for flashing the new firmware available [here](https://github.com/bcmi-labs/uno-r4-wifi-usb-bridge/blob/b1ddb36decd16f348e4e5796b2040c4b94b7e821/unor4wifi-updater/README.md)

Add UNO R4 WiFi basic support

---

src/property/Property.cpp

on sync events the `on-change` callback is invoked also if property is not changed
Create a sketch with one int property, connect the board and set the property value with a value widget, the property get synced. Stop network and restart it, the `on-change` callback is invoked also if the property value is not changed
Apply this changes the `on-change` callback is still called on the first sync event during first connection

Avoid calling onchange callback on sync event if property isn't changed

---

src/utility/time/TimeService.cpp

ST32H7 based boards and NANO RP2040 Connect shares the same mbed interface to configure and use the real time clock peripheral.

Time Service: merge STM42H7 and NANO RP2040 RTC functions

---

src/ArduinoIoTCloudTCP.cpp
src/utility/watchdog/Watchdog.cpp
src/utility/watchdog/Watchdog.h

Apply after #396 
Needs https://github.com/arduino/ArduinoCore-mbed/pull/779

Portenta H7 Watchdog: allow watchdog feeding using CATM1

---

src/AIoTC_Config.h
src/ArduinoECCX08Config.h

Needs https://github.com/arduino-libraries/ArduinoECCX08/pull/55

Add build configuration file for ECCX08

---

src/ArduinoIoTCloud.cpp
src/ArduinoIoTCloud.h

Fixes #402
warning can still be triggered from thingProperties.h file if deprecated functions are called.

Avoid library to call deprecated functions itself

---

examples/ArduinoIoTCloud-Advanced/ArduinoIoTCloud-Advanced.ino
examples/ArduinoIoTCloud-Advanced/arduino_secrets.h
examples/ArduinoIoTCloud-Advanced/thingProperties.h
examples/ArduinoIoTCloud-Basic/ArduinoIoTCloud-Basic.ino
examples/ArduinoIoTCloud-Basic/arduino_secrets.h
examples/ArduinoIoTCloud-Basic/thingProperties.h
examples/ArduinoIoTCloud-Callbacks/ArduinoIoTCloud-Callbacks.ino
examples/ArduinoIoTCloud-Callbacks/arduino_secrets.h
examples/ArduinoIoTCloud-Callbacks/thingProperties.h
examples/ArduinoIoTCloud-DeferredOTA/ArduinoIoTCloud-DeferredOTA.ino
examples/ArduinoIoTCloud-DeferredOTA/arduino_secrets.h
examples/ArduinoIoTCloud-DeferredOTA/thingProperties.h
examples/ArduinoIoTCloud-Schedule/ArduinoIoTCloud-Schedule.ino
examples/ArduinoIoTCloud-Schedule/arduino_secrets.h
examples/ArduinoIoTCloud-Schedule/thingProperties.h
examples/utility/ArduinoIoTCloud_Travis_CI/ArduinoIoTCloud_Travis_CI.ino
examples/utility/ArduinoIoTCloud_Travis_CI/arduino_secrets.h
examples/utility/ArduinoIoTCloud_Travis_CI/thingProperties.h

Make examples build on cloud web editor

---

.github/workflows/compile-examples.yml
.github/workflows/report-size-deltas.yml

The repository infrastructure uses the [**arduino/report-size-deltas**](https://github.com/arduino/report-size-deltas) GitHub Actions action to generate a report of the changes in memory usage of the example sketches that would result from merging a pull request.
There are two use patterns for the **arduino/report-size-deltas** action:
- [Run from a workflow triggered by a `schedule` event](https://github.com/arduino/report-size-deltas#run-from-a-scheduled-workflow)
- [Run from the same workflow as the "arduino/compile-sketches" action when triggered by a `pull_request` event](https://github.com/arduino/report-size-deltas#run-from-the-same-workflow-as-the-arduinocompile-sketches-action)
The latter use pattern is only suitable for private repositories. The reason is that, when a pull …

Fix size deltas report infrastructure configuration

---

library.properties

Recent change takes a dependency on `Arduino_SecureElement`, but failes to include the dependency in `library.properties`.

fix: Add dependency: `Arduino_SecureElement`

---

examples/ArduinoIoTCloud-Advanced/ArduinoIoTCloud-Advanced.ino
examples/ArduinoIoTCloud-Basic/ArduinoIoTCloud-Basic.ino
examples/ArduinoIoTCloud-Callbacks/ArduinoIoTCloud-Callbacks.ino
examples/ArduinoIoTCloud-DeferredOTA/ArduinoIoTCloud-DeferredOTA.ino
examples/ArduinoIoTCloud-Schedule/ArduinoIoTCloud-Schedule.ino
examples/utility/ArduinoIoTCloud_Travis_CI/ArduinoIoTCloud_Travis_CI.ino

Previous implementation was attempting to wait while "Serial was NOT ready" AND "time passed is GREATER than 5 seconds".
This can NEVER be true. Early logs were being missed and Serial had difficulty connecting during debugging.
It should have instead been waiting while "Serial was NOT ready" AND "time passed is LESS THAN OR EQUAL TO 5 seconds".

fix: Await Serial

---

src/ArduinoIoTCloudLPWAN.cpp

This PR fixes a bug introduced in https://github.com/arduino-libraries/ArduinoIoTCloud/pull/442
For TCP implementation the bug was already unintentionally fixed with https://github.com/arduino-libraries/ArduinoIoTCloud/pull/445 and https://github.com/arduino-libraries/ArduinoIoTCloud/pull/444

LPWAN: fix property container initialization

---

src/ArduinoIoTCloudDevice.cpp
src/ArduinoIoTCloudThing.cpp

Working on #457 i noticed two missing initializers in device class

ArduinoIoTCloudDevice: add missing initializers

---

src/ArduinoIoTCloudTCP.cpp

Bug was introduced with https://github.com/arduino-libraries/ArduinoIoTCloud/pull/445 already fixed in #455 using new command topic.
I tought it was better to backport and fix also for the property implementation.

Fix thing property reconfiguration after wifi loss

---

src/ArduinoIoTCloudTCP.cpp

It can provide useful feedback on why connection fails:
```
#define MQTT_CONNECTION_REFUSED            -2
#define MQTT_CONNECTION_TIMEOUT            -1
#define MQTT_SUCCESS                        0
#define MQTT_UNACCEPTABLE_PROTOCOL_VERSION  1
#define MQTT_IDENTIFIER_REJECTED            2
#define MQTT_SERVER_UNAVAILABLE             3
#define MQTT_BAD_USER_NAME_OR_PASSWORD      4
#define MQTT_NOT_AUTHORIZED                 5
```

Debug: print mqttClient error code when connection fails

---

.github/workflows/compile-examples.yml
src/ota/implementation/OTASTM32H7.cpp

This hotfix aims to solve the issue of corruption of the flash memory where the ota update is written

OTA: STM32H7 unmount filesystem before reset

---

src/ota/implementation/OTANanoRP2040.cpp
src/utility/watchdog/Watchdog.cpp
src/utility/watchdog/Watchdog.h

This is needed to allow ArduinoCellular library to kick the watchdog without using callback

Watchdog: use mbed API

---

.github/workflows/compile-examples.yml
src/utility/time/TimeService.cpp

TinyGSM has no UDP implementation so we should not use it. [This](https://github.com/pennam/Arduino_ConnectionHandler/blob/3ac5c054577481f5cc99c36bc87467b2b998d144/src/Arduino_CellularConnectionHandler.h#L37) should produce a compiler error 
Needs : 
- https://github.com/arduino-libraries/Arduino_Cellular/pull/12
- https://github.com/arduino-libraries/Arduino_Cellular/pull/13
- https://github.com/arduino-libraries/Arduino_Cellular/pull/14
- https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/119

Add Cellular support using Arduino Mid Carrier

---

src/ota/implementation/OTASTM32H7.cpp
src/ota/implementation/OTASTM32H7.h

STM32H7 OTA code cleanup

---

src/tls/utility/TLSClientMqtt.cpp
src/tls/utility/TLSClientOta.cpp

See changes 
Release :https://github.com/espressif/arduino-esp32/releases/tag/3.0.4
PR: https://github.com/espressif/arduino-esp32/pull/10101

ESP32: fix certificate bundle loading using core > 3.0.4

---

src/ArduinoIoTCloudTCP.cpp
src/ArduinoIoTCloudTCP.h
src/ota/interface/OTAInterface.cpp
src/ota/interface/OTAInterface.h
src/ota/interface/OTAInterfaceDefault.cpp
src/ota/interface/OTAInterfaceDefault.h

This pull request introduces several changes to the OTA update process in the Arduino IoT Cloud library. The key changes focus on improving the reliability of OTA updates by adding support for chunked downloads and refining OTA policy management.
Improvements to OTA policy management:
* [`src/ArduinoIoTCloudTCP.h`](diffhunk://#diff-a1314de94eb0792cf8632064de47dae933ca9243976b03715c1083d1faba2389L99-R110): Replaced `setOtaPolicies` with `enableOtaPolicy` and `disableOtaPolicy` methods to manage OTA policies more flexibly. Added a new method `setOTAChunkMode` to enable or disable chunked downloads.
* [`src/ota/interface/OTAInterface.cpp`](diffhunk://#diff-6e3e6582c41e8451a16dae10757ac9278c9c91a65567aab491f8f0eee40f33c9L170-R173): Updated the `otaAvailable` method to use the new …

OTA: chunked download

---

examples/ArduinoIoTCloud-Advanced/arduino_secrets.h
examples/ArduinoIoTCloud-Advanced/thingProperties.h
examples/ArduinoIoTCloud-Basic/arduino_secrets.h
examples/ArduinoIoTCloud-Basic/thingProperties.h
examples/ArduinoIoTCloud-BlockForOTA/arduino_secrets.h
examples/ArduinoIoTCloud-BlockForOTA/thingProperties.h
examples/ArduinoIoTCloud-Callbacks/arduino_secrets.h
examples/ArduinoIoTCloud-Callbacks/thingProperties.h
examples/ArduinoIoTCloud-DeferredOTA/arduino_secrets.h
examples/ArduinoIoTCloud-DeferredOTA/thingProperties.h
examples/ArduinoIoTCloud-Schedule/arduino_secrets.h
examples/ArduinoIoTCloud-Schedule/thingProperties.h
examples/utility/ArduinoIoTCloud_Travis_CI/arduino_secrets.h
examples/utility/ArduinoIoTCloud_Travis_CI/thingProperties.h

Otherwise username and password authentication is used by default for UNO R4 WiFi

examples: fix username/password secure element logic

---

.github/workflows/compile-examples.yml
examples/ArduinoIoTCloud-Schedule/arduino_secrets.h
examples/ArduinoIoTCloud-Schedule/thingProperties.h

Schedule property cannot work with TTN LoRa network unless board time is configured with `TimeService` [setSyncFunction](https://github.com/arduino-libraries/ArduinoIoTCloud/blob/8b7fbf4fc216f970a5af8d321deb02807e669da4/src/utility/time/TimeService.h#L52)
In the past there was an [attempt](https://github.com/arduino-libraries/ArduinoIoTCloud/commit/0cfc02f6d13ea347fc9b542b8a83d53b466e0e9b) to remove LoRa support from the example, but only the sketch comment was changed.
Fixes #495

examples: remova LoRa from schedule example

---

src/ArduinoIoTCloudTCP.cpp

It can happen that mqttclient disconnects during ota fetching. In this case we should also check for ota client state before go in disconnected state.
If ota client is still connected is better to give ota priority and try to finish to download before disconnect.

TCP: do not disconnect if ota client is connected

---

extras/test/CMakeLists.txt
extras/test/src/test_CloudFloat.cpp
extras/test/src/test_CloudWrapperFloat.cpp
src/property/math_utils.h
src/property/types/CloudFloat.h
src/property/types/CloudWrapperFloat.h

In the current version NAN values are not handled. This leads to unexpected behaviour since the numerical values of both the local variable and the cloud version are used to determine if there is a difference. Without this change a local variable that is initialized with a default of NAN will never receive the cloud value if the permission is set to `Write`. If the permission is set to `ReadWrite` the cloud value will always be overridden with NAN even with `onSync(CLOUD_WINS)`.
This PR explicitly handles the cases where either one of the values is NAN (non-equal), or both are NAN (equal).

Explicitly handle NAN values

---

extras/test/CMakeLists.txt
extras/test/src/test_command_decode.cpp
src/cbor/IoTCloudMessageDecoder.cpp

This PR aims to replace copyCBORStringToArray and copyCBORStringToArray calls to their counter version defined in cloud utils library.
This PR depends on https://github.com/arduino-libraries/Arduino_CloudUtils/pull/31

Removing copyCBORStringToArray and copyCBORStringToArray functions

---

src/ArduinoIoTCloudTCP.cpp

Fix the bug introduced with version 2.6.0 that crashes the Portenta H7 if used with the Cellular 4G connectivity

Fix the crash of Portenta H7 with cellular connectivity

---

src/ArduinoIoTCloudTCP.cpp
src/cbor/IoTCloudMessageDecoder.cpp
src/cbor/IoTCloudMessageDecoder.h
src/cbor/IoTCloudMessageEncoder.cpp
src/cbor/IoTCloudMessageEncoder.h

Addressing https://github.com/arduino-libraries/ArduinoIoTCloud/issues/552. While using platformio build system some new structures are not included in the final binary, for this reason it is required for concrete encoder and decoder for cbor commands to be referenced in files that are referenced by the sketch entrypoint.

Addressing Issue #552

---

examples/utility/Provisioning_2.0/ClaimingHandler.cpp
examples/utility/Provisioning_2.0/ClaimingHandler.h
examples/utility/Provisioning_2.0/Provisioning_2.0.ino

- generate private key if fails in generating the token
- send the public key on request

Changes for migration from Provisioning 1.0 to Provisioning 2.0 
