src/ConnectionManager.h, src/EthernetConnectionManager.cpp, src/EthernetConnectionManager.h, src/GSMConnectionManager.cpp, src/GSMConnectionManager.h, src/WiFiConnectionManager.cpp, src/WiFiConnectionManager.h, src/utility/DebugUtils.cpp, src/utility/DebugUtils.h, src/utility/NTPUtils.cpp
No change in logic/functionality of the implementation.
=> Refactoring: Separating definition/implementation and other minor cleanups

examples/utility/Provisioning/Provisioning.ino, src/ArduinoIoTCloud.cpp, src/ArduinoIoTCloud.h
The id we are storing on the crypto chip is actually the **device** id, it has nothing to do with a **thing**.
=> change thing id to device id

src/ArduinoIoTCloud.cpp, src/EthernetConnectionManager.cpp, src/GSMConnectionManager.cpp, src/WiFiConnectionManager.cpp, src/utility/DebugUtils.cpp, src/utility/DebugUtils.h
Warning - not yet polished and done - intention is to show what's possible :smiley:
=> Simplify debug message with variadic arguments

src/ArduinoIoTCloud.cpp, src/ArduinoIoTCloud.h
**Usage**
```C++
void setup() {
/* ... */
ArduinoCloud.addCallback(ArduinoIoTCloudEvent::SYNC, &onSync);
ArduinoCloud.addCallback(ArduinoIoTCloudEvent::CONNECT, &onConnect);
ArduinoCloud.addCallback(ArduinoIoTCloudEvent::DISCONNECT, &onDisconnect);
/* ... */
}
/* ... */
void onSync(void * arg) {
Serial.println("onSync");
}
void onConnect(void * arg) {
Serial.println("onConnect");
}
void onDisconnect(void * arg) {
Serial.println("onDisconnect");
}
```
=> Event callbacks for various cloud events

src/ArduinoIoTCloud.cpp, src/ArduinoIoTCloud.h
First draft of multi value properties implementation: phase 2 and 3
=> Multi value properties implementation

.github/workflows/compile-examples.yml, library.properties
from `library.properties` and `compile-examples.yml`.
=> Removing ArduinoBearSSL dependency

keywords.txt
=> Adding keywords.txt for syntax highlighting in Arduino IDE

extras/tools/README.md, extras/tools/bin2ota.py
CC @eclipse1985 @zmoog
@zmoog Does this produce the same binary output as your builder extension?
=> OTA Header set compression flag

src/ArduinoIoTCloudTCP.cpp, src/ArduinoIoTCloudTCP.h
All other OTA function are already in, only this one was missing
=> Move sendOTAPropertiesToCloud() inside #if OTA_ENABLED

README.md
Added missing boards to the readme list
=> README: Add Nicla Vision and Nano RP2040 Connect

src/tls/BearSSLClient.cpp
FIxes #300, See https://github.com/arduino-libraries/ArduinoBearSSL/issues/60 and https://github.com/arduino-libraries/ArduinoBearSSL/pull/61
=> fix write() in BearSSLClient.cpp

src/tls/BearSSLClient.h, src/tls/profile/aiotc_profile.c, src/tls/utility/Cert.h, src/utility/ota/OTA-samd.cpp, src/utility/time/NTPUtils.h, src/utility/watchdog/Watchdog.cpp
Just a round on compilation warnings
=> Fix compilation warnings

extras/test/CMakeLists.txt, extras/test/external/catch/v2.13.10/include/catch.hpp
This fixes: https://github.com/arduino-libraries/ArduinoIoTCloud/actions/runs/3591116258/jobs/6045272685
Reference to catch issue: https://github.com/catchorg/Catch2/issues/2421
=> Unit tests: update catch to v2.13.10

extras/tools/bin2ota.py
Add Nicla Vision and Opta to bin2ota script
=> bin2ota Add missing boards

library.properties
=> Add Arduino_Portenta_OTA to library dependencies

src/utility/ota/FlashSHA256.cpp
Fix typo to make spell check happy
=> Fix typo in comments

src/AIoTC_Config.h
Some leftover from https://github.com/arduino-libraries/ArduinoIoTCloud/pull/311
=> Remove remaining ARDUINO_AVR_UNO_WIFI_REV2 configuration defines

examples/utility/ArduinoIoTCloud_Travis_CI/thingProperties.h
ArduinoCloud.setThingId(THING_ID); is called from all LoRa sketches geenrated from the Cloud editor
=> Add setThingId call in Travic_CI sketch to ensure checking function existance

src/utility/time/TimeService.cpp
Closed #462 by mistake. Rebased and re-opened @zfields
=> fix: Warnings

src/ota/interface/OTAInterfaceDefault.cpp, src/ota/interface/OTAInterfaceDefault.h
=> OTA: increase download time to 2s

src/ota/interface/OTAInterfaceDefault.cpp
=> OTA: check for client connected during fetch

src/ota/interface/OTAInterfaceDefault.cpp
=> OTA: fix sign-compare compiler warnings

examples/ArduinoIoTCloud-BlockForOTA/ArduinoIoTCloud-BlockForOTA.ino, examples/ArduinoIoTCloud-BlockForOTA/arduino_secrets.h, examples/ArduinoIoTCloud-BlockForOTA/thingProperties.h
=> Add "Block for OTA" example

src/ArduinoIoTCloudLPWAN.cpp, src/ArduinoIoTCloudNotecard.cpp, src/ArduinoIoTCloudTCP.cpp
Simple change to add useful information about library version
=> Print library version inside debug info

src/ArduinoIoTCloudDevice.cpp, src/message/Commands.h
- send the WiFi FW version to cloud
This PR relies on https://github.com/arduino-libraries/Arduino_CloudUtils/pull/33
=> Send WiFi version after connection to cloud
